### ISSUE TITLE
Share todo list and task

### ISSUE THREAD

**Issue by 0xC0FFEEC0DE** [SecUSo/privacy-friendly-todo-list#128]
A todo list / task should be shareable via the system-share-feature.
The list should be shared as plain text in markdown format.
Example:
````
### My To-Do List

- [x] Task 1 (Description of Task 1)

- [ ] Deadline Sep 2, 2024: Task 2
    - [x] Subtask 1
    - [ ] Subtask 2

- [x] Task 3

- [ ] Task 4
    - [ ] Subtask 1
    - [x] Subtask 2
````
Result after markdown interpretation:

### My To-Do List

- [x] Task 1 (Description of Task 1)

- [ ] Deadline Sep 2, 2024: Task 2
    - [x] Subtask 1
    - [ ] Subtask 2

- [x] Task 3

- [ ] Task 4
    - [ ] Subtask 1
    - [x] Subtask 2

**Comment by 0xC0FFEEC0DE** [comment]
Done with commit 02b4cb014b.
